apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Release.Namespace }}
  annotations: 
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-monitor-path: "/"
spec:
  rules:
    - host: dev-api.paymentapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-api-service
                port:
                  number: {{ .Values.paymentApi.service.port }}