{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Release.Namespace }}
  annotations: 
    # ---------------------------------------------------------
    # Logic for AGIC (Azure Application Gateway)
    # ---------------------------------------------------------
    {{- if eq .Values.ingress.className "azure-application-gateway" }}
    appgw.ingress.kubernetes.io/health-monitor-path: "/"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/request-timeout: "60"
    {{- end }}


    # ---------------------------------------------------------
    # Logic for Nginx Ingress Controller
    # ---------------------------------------------------------
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    {{- end }}

    # ---------------------------------------------------------
    # User annotations
    # ---------------------------------------------------------
    {{- with .Values.ingress.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  # Set controller to ingress
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
{{- end }}