apiVersion: v1
kind: Service
metadata:
  name: payment-worker-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.paymentWorker.service.type }}
  ports:
  - port: {{ .Values.paymentWorker.service.port }}
    targetPort: {{ .Values.paymentWorker.deployment.exposePort }}
  selector:
    app.kubernetes.io/name: {{ .Values.paymentWorker.deployment.appLabel }}