{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payment-worker-nw-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.paymentWorker.deployment.appLabel }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Values.paymentApi.deployment.appLabel }}
      ports:
        - protocol: TCP
          port: {{ .Values.paymentWorker.deployment.exposePort }}
{{- end }}