{{- if .Values.paymentApi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-api-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.paymentApi.deployment.name }}
  minReplicas: {{ .Values.paymentApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.paymentApi.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.paymentApi.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}