apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.paymentApi.service.type }}
  ports:
  - port: {{ .Values.paymentApi.service.port }}
    targetPort: {{ .Values.paymentApi.deployment.exposePort }}
  selector:
    app.kubernetes.io/name: {{ .Values.paymentApi.deployment.appLabel }}