apiVersion: v1
kind: Secret
metadata:
  name: payment-api-db-credentials
type: Opaque
data:
  PAYMENT_DB_URL: {{ .Values.paymentApi.db.PAYMENT_DB_URL }}
  PAYMENT_DB_PASSWORD: {{ .Values.paymentApi.db.PAYMENT_DB_PASSWORD }}
  PAYMENT_DB_USER: {{ .Values.paymentApi.db.PAYMENT_DB_USER }}