# 
# PaymentApi config
# 
paymentApi:
  env:
    PAYMENT_WORKER_BASE_URL: "http://payment-worker-service" # service name

  db:
    PAYMENT_DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vamF2YXNlcnZpY2VhcHBwc3FsZmxleHNlcnZlci5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9wYXltZW50cw==  # example jdbc:postgresql://localhost:5432/payments
    PAYMENT_DB_PASSWORD: SEBTaDFDb1IzIQ==
    PAYMENT_DB_USER: cHNxbGFkbWlu

  deployment:
    name: payment-api-deployment
    appLabel: payment-api
    replicas: 1
    exposePort: 8080
    image:
      repository: javaservicescontainerregistry123.azurecr.io/javaapps/payment-api
      tag: 1.0.1
    resources:
      enabled: true # Do you want limit resource?
      requests:
        memory: "400Mi"
        cpu: "200m"
      limits:
        memory: "700Mi"
        cpu: "400m"
    livenessProbe:
      enabled: true
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 2
      failureThreshold: 3
      successThreshold: 1

  service:
    type: ClusterIP # LoadBalancer # changed to cluster for AGIC ingress
    port: 80

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

# 
# PaymentWorker config
# 
paymentWorker:
  env:
    PAYMENT_WORKER_PORT: 8090 # remember that image must expose that port
    PAYMENT_API_BASE_URL: "http://payment-api-service" # service name
    WORKER_CPU_LOAD_MS: 500

  deployment:
    name: payment-worker-deployment
    appLabel: payment-worker
    replicas: 1
    exposePort: 8090
    image:
      repository: javaservicescontainerregistry123.azurecr.io/javaapps/payment-worker
      tag: 1.0.0
    resources:
      enabled: true # Do you want limit resource?
      requests:
        memory: "400Mi"
        cpu: "200m"
      limits:
        memory: "600Mi"
        cpu: "400m"
    livenessProbe:
      enabled: true
      path: /actuator/health
      port: 8090
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      path: /actuator/health
      port: 8090
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 2
      failureThreshold: 3
      successThreshold: 1

  service:
    type: ClusterIP # LoadBalancer # changed to cluster for AGIC ingress
    port: 80

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50