apiVersion: v1
kind: Secret
metadata:
  name: payment-api-db-credentials
type: Opaque
data:
  PAYMENT_DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vamF2YXNlcnZpY2VhcHBwc3FsZmxleHNlcnZlci5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9wYXltZW50cw==
  PAYMENT_DB_PASSWORD: SEBTaDFDb1IzIQ==
  PAYMENT_DB_USER: cHNxbGFkbWlu