################################################
# Helm values without ingress, hovever with payment-api service of type LoadBalancer
################################################

#
# Ingress config
#
ingress:
  enabled: false

# 
# PaymentApi config
# 
paymentApi:
  service:
    type: LoadBalancer
    port: 80