################################################
# Helm values with NGINX Ingress for API Payment Service
################################################

#
# Ingress config
#
ingress:
  enabled: true
  # set to "azure-application-gateway" to enable AGIC specific annotations
  # set "nginx" for nginx ingress controller
  className: "nginx"